/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class leon_training_ndk_patch_Client */

#ifndef _Included_leon_training_ndk_patch_Client
#define _Included_leon_training_ndk_patch_Client
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     leon_training_ndk_patch_Client
 * Method:    bsdiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_leon_training_ndk_patch_Client_bsdiff
        (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     leon_training_ndk_patch_Client
 * Method:    bspatch
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_leon_training_ndk_patch_Client_bspatch
        (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
