/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class leon_training_ndk_splistmerge_Client */

/**
 * 向手机发送信息
 */
void showCharMsg(JNIEnv *, char *);
void showStrMsg(JNIEnv *, jstring);