/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class leon_training_thread_jniposix_Client */

#ifndef _Included_leon_training_thread_jniposix_Client
#define _Included_leon_training_thread_jniposix_Client
#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT void JNICALL Java_leon_training_thread_jniposix_Client_initJni
        (JNIEnv *, jclass);


JNIEXPORT void JNICALL Java_leon_training_thread_jniposix_Client_destroyJni
        (JNIEnv *, jclass);


JNIEXPORT void JNICALL Java_leon_training_thread_jniposix_Client_pthread
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
