/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class leon_training_thread_jniposix_Client */

#ifndef _Included_leon_training_thread_jniposix_Client
#define _Included_leon_training_thread_jniposix_Client
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     leon_training_thread_jniposix_Client
 * Method:    initJni
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_leon_training_thread_jniposix_Client_initJni
  (JNIEnv *, jclass);

/*
 * Class:     leon_training_thread_jniposix_Client
 * Method:    destroyJni
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_leon_training_thread_jniposix_Client_destroyJni
  (JNIEnv *, jclass);

/*
 * Class:     leon_training_thread_jniposix_Client
 * Method:    pthread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_leon_training_thread_jniposix_Client_pthread
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
