/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class leon_training_ndk_splistmerge_Client */

#ifndef _Included_leon_training_ndk_splistmerge_Client
#define _Included_leon_training_ndk_splistmerge_Client
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     leon_training_ndk_splistmerge_Client
 * Method:    splitFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jint JNICALL Java_leon_training_ndk_splistmerge_Client_splitFile
        (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     leon_training_ndk_splistmerge_Client
 * Method:    mergeFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jint JNICALL Java_leon_training_ndk_splistmerge_Client_mergeFile
        (JNIEnv *, jclass, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
