/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class leon_training_ndk_hotfix_NativeFix */

#ifndef _Included_leon_training_ndk_hotfix_NativeFix
#define _Included_leon_training_ndk_hotfix_NativeFix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     leon_training_ndk_hotfix_NativeFix
 * Method:    init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_leon_training_ndk_hotfix_NativeFix_init
  (JNIEnv *, jclass, jint);

/*
 * Class:     leon_training_ndk_hotfix_NativeFix
 * Method:    replaceMethod
 * Signature: (Ljava/lang/reflect/Method;Ljava/lang/reflect/Method;)V
 */
JNIEXPORT void JNICALL Java_leon_training_ndk_hotfix_NativeFix_replaceMethod
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
