/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class leon_training_ndk_opensles_OpenESPlayer */

#ifndef _Included_leon_training_ndk_opensles_OpenESPlayer
#define _Included_leon_training_ndk_opensles_OpenESPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     leon_training_ndk_opensles_OpenESPlayer
 * Method:    play
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_leon_training_ndk_opensles_OpenESPlayer_play
  (JNIEnv *, jclass, jstring);

/*
 * Class:     leon_training_ndk_opensles_OpenESPlayer
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_leon_training_ndk_opensles_OpenESPlayer_stop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
